// components/TagList.tsx
import { Tag } from "@/types";

export const tagList: Tag[] = [
  // 既存のタグ
  { id: "12星座", name: "12星座", count: 25 },
  { id: "牡羊座", name: "牡羊座", count: 25 },
  { id: "牡牛座", name: "牡牛座", count: 18 },
  { id: "双子座", name: "双子座", count: 15 },
  { id: "蟹座", name: "蟹座", count: 14 },
  { id: "獅子座", name: "獅子座", count: 13 },
  { id: "乙女座", name: "乙女座", count: 12 },
  { id: "天秤座", name: "天秤座", count: 12 },
  { id: "蠍座", name: "蠍座", count: 11 },
  { id: "射手座", name: "射手座", count: 10 },
  { id: "山羊座", name: "山羊座", count: 9 },
  { id: "水瓶座", name: "水瓶座", count: 8 },
  { id: "魚座", name: "魚座", count: 7 },

  // 惑星など
  { id: "惑星", name: "惑星", count: 20 },
  { id: "小惑星", name: "小惑星", count: 20 },
  { id: "太陽", name: "太陽", count: 20 },
  { id: "月", name: "月", count: 18 },
  { id: "水星", name: "水星", count: 17 },
  { id: "金星", name: "金星", count: 16 },
  { id: "火星", name: "火星", count: 15 },
  { id: "木星", name: "木星", count: 14 },
  { id: "土星", name: "土星", count: 13 },
  { id: "天王星", name: "天王星", count: 12 },
  { id: "海王星", name: "海王星", count: 11 },
  { id: "冥王星", name: "冥王星", count: 10 },
  { id: "ドラゴンヘッド", name: "ドラゴンヘッド", count: 8 },
  { id: "ドラゴンテイル", name: "ドラゴンテイル", count: 7 },
  { id: "リリス", name: "リリス", count: 6 },
  { id: "カイロン", name: "カイロン", count: 6 },
  { id: "セレス", name: "セレス", count: 6 },
  { id: "パラス", name: "パラス", count: 6 },
  { id: "ジュノー", name: "ジュノー", count: 6 },
  { id: "ベスタ", name: "ベスタ", count: 6 },

  // 各種技法など
  { id: "アセンダント", name: "アセンダント", count: 5 },
  { id: "ディセンダント", name: "ディセンダント", count: 5 },
  { id: "トランジット", name: "トランジット", count: 5 },
  { id: "ネイタル", name: "ネイタル", count: 5 },
  { id: "プログレス", name: "プログレス", count: 5 },
  { id: "過去世", name: "過去世", count: 5 },
  { id: "事件・事故", name: "事件・事故", count: 5 },
  { id: "有名人", name: "有名人", count: 5 },
  { id: "アスペクト", name: "アスペクト", count: 5 },
  { id: "サビアン", name: "サビアン", count: 5 },

  // ハウス 1〜12
  { id: "1ハウス", name: "1ハウス", count: 3 },
  { id: "2ハウス", name: "2ハウス", count: 3 },
  { id: "3ハウス", name: "3ハウス", count: 3 },
  { id: "4ハウス", name: "4ハウス", count: 3 },
  { id: "5ハウス", name: "5ハウス", count: 3 },
  { id: "6ハウス", name: "6ハウス", count: 3 },
  { id: "7ハウス", name: "7ハウス", count: 3 },
  { id: "8ハウス", name: "8ハウス", count: 3 },
  { id: "9ハウス", name: "9ハウス", count: 3 },
  { id: "10ハウス", name: "10ハウス", count: 3 },
  { id: "11ハウス", name: "11ハウス", count: 3 },
  { id: "12ハウス", name: "12ハウス", count: 3 },
];
